name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master
  commit:
    branches:
      -main
      -master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitfolio:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 23
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gitfolio:latest
            docker stop gitfolio || true
            docker rm gitfolio || true
            docker run -d --name gitfolio -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/gitfolio:latest
